<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>x64</Platforms>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
		<PackageReference Include="System.Management" Version="8.0.0" />
	</ItemGroup>
</Project>